### ISSUE TITLE
双系统切换问题！

### ISSUE THREAD

**Issue by vineshine** [laobamac/Hackintosh-i7-8700K-ASUS-PRIME-Z370-A-Z370-F#1]
作者你好，EFI已经使用上了，很完美。我是先安装了Windows10，后使用黑果小兵的镜像并将EFI替换为作者的，macOS能正常使用，但无法切换到Windows10了，具体问题如下：开机到OC引导界面，选择Windows启动项并回车后，会自动重启又回到OC界面，无法进入Windows。这个问题可以帮忙解决下吗，谢谢！

**Comment by laobamac** [comment]
Thanks for your advice.This problem is solved by SSDTs,please go to README.md for more information.
