### ISSUE TITLE
Couldn't install macOS Sonoma

### ISSUE THREAD

**Issue by vilifi1** [laobamac/Hackintosh-i7-8700K-ASUS-PRIME-Z370-A-Z370-F#2]
Hello！Thanks for your great EFI at first.I used it to install macOS Monterey and Ventura successfully and it worked very perfect.But when I tried installing macOS 14,it seemed to be bad.Starting process stopped at 'AirportFixip' and 'PCI CONFIGURATION END'.Could you fix it soon？Thanks so much.

**Comment by laobamac** [comment]
Hi！Thanks for your advice.It caused by brcm drivers.Due to the IO80211Family has changed a lot in Sonoma,you must delete airportfixup in EFI.I'll fix it these days.
